[project]
name = "detecting-diabetic-retinopathy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kaggle>=1.7.4.5",
    "kagglehub>=0.3.12",
]
